spring:
  profiles:
    include: global
    active: prod
    #注意各个yaml文件的命名规则applications-${profile}.yaml
  thymeleaf:
    cache: false # 开发时禁止thymeleaf缓存否则会无法实时显示更新的静态文件
  flyway:
    locations: classpath:/db/migration
  servlet:
    multipart:
      max-request-size: 10MB #限制单个文件的最大值
      max-file-size: 10MB #限制多个文件的总大小
  mail:
    host: ${npe.mail.host}
    username: ${npe.mail.username}
    # qq邮箱授权码
    password: ${npe.mail.password}
    protocol: ${npe.mail.protocol}
    port: ${npe.mail.port}
    properties.mail.smtp:
      # 465端口是为SMTPS（SMTP-over-SSL）所以需要加上下面一句话，否则会报错
      # Got bad greeting from SMTP host: smtp.qq.com, port: 465, response: [EOF]
      ssl.enable: true
      auth: true
      starttls.enable: true
      starttls.required: true
    default-encoding: UTF-8

  redis:
    # redis 数据库索引(默认0)
    database: ${npe.redis.database}
    # redis 服务器地址
    host: ${npe.redis.host}
    # redis 服务器连接端口
    port: ${npe.redis.port}
    # redis 服务器连接密码(默认为空)
    password: ${npe.redis.password}
    # password:
    lettuce:
      pool:
        # redis 连接池最大连接数(负值表示没有限制)
        max-active: 300
        # redis 连接池最大阻塞的带时间(负值表示没有限制)
        max-wait: -1
        # redis 连接池中最大空闲连接
        max-idle: 100
        # redis 连接池中最小空闲连接
        min-idle: 8
    # redis 连接超时时间(毫秒)
    timeout: 5000
    ## redis存在超时的问题暂时加大超时时间来应对，但是从500ms->增大到5000ms之后还有这个问题。尝试扩大连接池最大连接数
mybatis:
  type-aliases-package: com.smallclover.nullpointerexception.model
  mapper-locations: classpath:mapper/*/*.xml

# 打印日志级别
# logging:
#  pattern:
    # 日志输出的格式
    # 只限于控制台？
#    console: "%d - %msg%n"
    # 指定的包或者类的日志输出级别
#  level:
#    com.smallclover.nullpointerexception: debug
    # 如果之声明了这个配置，那么会在当前项目的根目录输出一个日志
#  file:
#    name: test_log.log
# 日志级别
# TRACE < DEBUG < INFO < WARN < ERROR < FATAL